#@package _global_

defaults:
  - override /dataset: context_batch
  - override /datamodule: base_datamodule
  - override /model: crossformer
  - override /optimization: warmup_reduce_on_plateau_adam

task_definition:
  requires_training: true

model:
  ts_in: ${task_definition.seq_len}
  ts_out: ${task_definition.pred_len}
  d_yc: ${infer_data_dim:target,-1}
  d_yt: ${infer_data_dim:target,-1}
  d_x: ${infer_data_dim:features,-1}

warmup_steps: 10000
decay_factor: 0.9
init_lr: 1.0e-10
base_lr: 5.0e-4
patience: 5
