scaler_features:
  transform:
    _target_: picid.transforms.base_transforms.scaler.MinMaxScalerSklearn

  metadata:
    apply_to: features
    fit_on: train

ragged_regular_ragged_target:
  transform:
    _target_: picid.transforms.base_transforms.identity.IdentityPassThrough

  metadata:
    apply_to: target
    assign_to:
      target: fault_classification
