_evaluator_defaults: &evaluator_defaults
  _target_: picid.evaluator.default.DefaultEvaluator

  metric_names: ["mae", "mse", "rmse", "nasa_score"]

  apply_inverse_scaling: False
  inverse_transform_name: null
  save_predictions: False

  # Some models predict always a multivariate time-series but then at evaluation we have to evaluate on one particular variable, hence here is a proposition how to tackle such cases
  task_mode: ${datasource.task_mode} # univariate/multivariate
  paths: ${paths}

train: *evaluator_defaults
val: *evaluator_defaults
test:
  <<: *evaluator_defaults
  save_predictions: True
