# subsample_features:
#   transform:
#     _target_: picid.transforms.base_transforms.subsample.SubsampleTransform
#     step: 10
#   metadata:
#     apply_to: features

scaler_features:
  transform:
    _target_: picid.transforms.base_transforms.scaler.StandardScalerSklearn

  metadata:
    apply_to: features
    fit_on: train

take_last_target:
  transform:
    _target_: picid.transforms.base_transforms.subsample.WindowedAggregationTransform
    step: 1 # TO BE CHANGED SOMEHOW
    window_size: full
    aggregation: last
    dim: 1
  metadata:
    apply_to: target

# Reduce target dim
reshape_target:
  transform:
    _target_: picid.transforms.base_transforms.reshaping.ReshapeTransform
    pattern: "a 1 1 -> a 1"
  metadata:
    apply_to: target

scaler_target:
  transform:
    _target_: picid.transforms.bearings.health_index.HealthIndexTransform
    runtime_key: target
    unit_key: unit_id
    dataset_name: PRONOSTIA

  metadata:
    apply_to: ["target", "unit_id"]
    assign_to: rul

############# CumSum Feature #################
cumsum_feature:
  transform:
    _target_: picid.transforms.signal_processing.cumsum.CumSumTransform

  metadata:
    apply_to: "features"
    assign_to: "cumsum_feature"

take_last_cumsum:
  transform:
    _target_: picid.transforms.base_transforms.subsample.WindowedAggregationTransform
    step: 1 # TO BE CHANGED SOMEHOW
    window_size: full
    aggregation: last
    dim: 0
  metadata:
    apply_to: cumsum_feature

cumsum_feature_scaler:
  transform:
    _target_: picid.transforms.base_transforms.scaler.MinMaxScalerSklearn

  metadata:
    apply_to: cumsum_feature
    fit_on: train

# Reduce target dim
reshape_cumsum:
  transform:
    _target_: picid.transforms.base_transforms.reshaping.ReshapeTransform
    pattern: "1 a -> a"
  metadata:
    apply_to: cumsum_feature

ragged2regular_cumsum_feature:
  transform:
    _target_: picid.transforms.base_transforms.shape_manipulations.RegularizeRaggedDataTransform

  metadata:
    apply_to: "cumsum_feature"

time_domain_features:
  transform:
    _target_: picid.transforms.base_transforms.time_statistics.TimeStatsTransform
    hankel_window_size: 200
    stats_to_compute: [
        "mean",
        "maximum",
        "minimum",
        "root_mean_square",
        "abs_avg", # Defined as a wrapper for root_mean_square in the source
        "peak_to_peak_value",
        "standard_deviation",
        "skewness",
        "kurtosis",
        "variance",
        "peak_factor",
        "change_coefficient", # Note: This is mean / std
        "clearance_factor",
        "abs_energy",
        "hankel_svd",
      ]

  metadata:
    apply_to: "features"
    assign_to: "time_domain_features"

ragged2regular_time_domain_features:
  transform:
    _target_: picid.transforms.base_transforms.shape_manipulations.RegularizeRaggedDataTransform

  metadata:
    apply_to: "time_domain_features"

############# Spectral Statistics Features #################

spectral_domain_features:
  transform:
    _target_: picid.transforms.base_transforms.spectral.SpectralStatsTransform

    stats_to_compute: [
        "mean",
        "maximum",
        "minimum",
        "root_mean_square",
        "peak_to_peak_value",
        "variance",
        "skewness",
        "kurtosis",
        "abs_energy",
        # rul_features inspired
        "peak_factor",
        "change_coefficient",
        "clearance_factor",
        # Entropy stats
        "spectral_entropy",
        "shannon_entropy",
        "permutation_entropy",
      ]

  metadata:
    apply_to: "features"
    assign_to: "spectral_features"

ragged2regular_spectral_features:
  transform:
    _target_: picid.transforms.base_transforms.shape_manipulations.RegularizeRaggedDataTransform

  metadata:
    apply_to: "spectral_features"

concatenate_features:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.concatenate.ConcatenateTransform

  metadata:
    apply_to: [
        "spectral_features",
        "time_domain_features",
        "cumsum_feature",
        # "features_stft",
      ]
    assign_to: features

final_scaler_features:
  transform:
    _target_: picid.transforms.base_transforms.scaler.MinMaxScalerSklearn

  metadata:
    apply_to: features
    fit_on: train
    cache_point: True

# plot_features_final:
#   transform:
#     unit_key: unit_id
#     _target_: picid.transforms.visualization.features_target_plotter.FeatureTargetPlotter
#     saving_path: ${paths.log_dir}/images_subsampled
#     features_key: features
#     target_key: target

#   metadata:
#     apply_to: ["features", "target", "unit_id"]
