scaler_features:
  transform:
    _target_: picid.transforms.base_transforms.scaler.StandardScalerSklearn

  metadata:
    apply_to: features
    fit_on: train

take_last_target:
  transform:
    _target_: picid.transforms.base_transforms.subsample.WindowedAggregationTransform
    step: 60
    window_size: full
    aggregation: last
    dim: 1
  metadata:
    apply_to: target

# Reduce target dim
reshape_target:
  transform:
    _target_: picid.transforms.base_transforms.reshaping.ReshapeTransform
    pattern: "a 1 1 -> a 1"
  metadata:
    apply_to: target

scaler_target:
  transform:
    _target_: picid.transforms.bearings.health_index.HealthIndexTransform
    runtime_key: target
    unit_key: unit_id
    dataset_name: PRONOSTIA

  metadata:
    apply_to: ["target", "unit_id"]
    assign_to: rul

spectral_features:
  transform:
    _target_: picid.transforms.base_transforms.spectral.SpectralStatsTransform
    stats_to_compute: [
        "mean",
        "maximum",
        "minimum",
        "root_mean_square",
        "peak_to_peak_value",
        "variance",
        "skewness",
        "kurtosis",
        "abs_energy",
        # rul_features inspired
        "peak_factor",
        "change_coefficient",
        "clearance_factor",
        # Entropy stats
        "spectral_entropy",
        "shannon_entropy",
        "permutation_entropy",
      ]

  metadata:
    apply_to: "features"
    assign_to: "features"

sequence2statistics:
  transform:
    _target_: picid.transforms.battery.sequence2statistics.Sequence2Statistics
    padding_value: null

  metadata:
    apply_to: "features"

ragged2regularragged:
  transform:
    _target_: picid.transforms.base_transforms.shape_manipulations.RegularizeRaggedDataTransform

  metadata:
    apply_to: "features"
