scaler_features:
  transform:
    _target_: picid.transforms.base_transforms.scaler.MinMaxScalerSklearn

  metadata:
    apply_to: features
    fit_on: train

# Why do we have this transform now? To make dataset batching work over the dim=0 (in other words the first unraged dimension)
ragged_regular_ragged_target:
  transform:
    _target_: picid.transforms.base_transforms.shape_manipulations.RegularizeRaggedDataTransform

  metadata:
    apply_to: target
    assign_to: anomaly_detection
# Output shape is (N,1,1)

# Reduce target dim
reshape_target:
  transform:
    _target_: picid.transforms.base_transforms.reshaping.ReshapeTransform
    pattern: "a 1 1 -> a 1"
  metadata:
    apply_to: anomaly_detection
# Output shape is (N,1)


# Create time-domain and spectral-domain features
time_domain_features:
  transform:
    _target_: picid.transforms.base_transforms.time_statistics.TimeStatsTransform
    hankel_window_size: 500
    stats_to_compute: [
        "mean",
        "maximum",
        "minimum",
        "root_mean_square",
        "abs_avg", # Defined as a wrapper for root_mean_square in the source
        #"peak_to_peak_value",
        #"standard_deviation",

        #"skewness",
        # "kurtosis",

        #"variance",
        #"peak_factor",
        #"change_coefficient", # Note: This is mean / std
        #"clearance_factor",
        #"abs_energy",

        #"hankel_svd",
      ]

  metadata:
    apply_to: "features"
    assign_to: "time_domain_features"

ragged2regular_time_domain_features:
  transform:
    _target_: picid.transforms.base_transforms.shape_manipulations.RegularizeRaggedDataTransform

  metadata:
    apply_to: "time_domain_features"


spectral_domain_features:
  transform:
    _target_: picid.transforms.base_transforms.spectral.SpectralStatsTransform

    stats_to_compute: [
        "mean",
        "maximum",
        "minimum",
        "root_mean_square",
        #"peak_to_peak_value",
        #"variance",
        #"skewness",
        #"kurtosis",
        #"abs_energy",
        # rul_features inspired
        #"peak_factor",
        #"change_coefficient",
        #"clearance_factor",
        # Entropy stats
        #"spectral_entropy",
        #"shannon_entropy",
        # "permutation_entropy",
      ]

  metadata:
    apply_to: "features"
    assign_to: "spectral_features"

ragged2regular_spectral_features:
  transform:
    _target_: picid.transforms.base_transforms.shape_manipulations.RegularizeRaggedDataTransform

  metadata:
    apply_to: "spectral_features"

concatenate_features:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.concatenate.ConcatenateTransform

  metadata:
    apply_to: ["spectral_features", "time_domain_features"]
    assign_to: features

final_scaler_features:
  transform:
    _target_: picid.transforms.base_transforms.scaler.MinMaxScalerSklearn

  metadata:
    apply_to: features
    fit_on: train
