defaults:
  - airbus_helicopter/default@_here_

# --- Base blocks --------------------------------------------------------

__tabularize_x_transform: &__tabularize_x_transform
  _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
  seq_len: ${task_definition.seq_len}
  label_len: ${task_definition.label_len}
  pred_len: ${task_definition.pred_len}
  timestep_dimension: 1
  select_features:
    - features: history

__tabularize_y_transform: &__tabularize_y_transform
  _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
  seq_len: ${task_definition.seq_len}
  label_len: ${task_definition.label_len}
  pred_len: ${task_definition.pred_len}
  timestep_dimension: 1
  select_features:
    - anomaly_detection: present

__tabularize_x_metadata: &__tabularize_x_metadata
  apply_to: ["features"]
  assign_to: features

__tabularize_y_metadata: &__tabularize_y_metadata
  apply_to: ["anomaly_detection"]
  assign_to: anomaly_detection

# --- Derived transforms -------------------------------------------------

tabularize_x_train:
  transform:
    <<: *__tabularize_x_transform
    stride: ${task_definition.stride_train}
  metadata:
    <<: *__tabularize_x_metadata
    transform_on_keys: ["train"]

tabularize_y_train:
  transform:
    <<: *__tabularize_y_transform
    stride: ${task_definition.stride_train}
  metadata:
    <<: *__tabularize_y_metadata
    transform_on_keys: ["train"]

tabularize_x_val_test:
  transform:
    <<: *__tabularize_x_transform
    stride: ${task_definition.stride}
  metadata:
    <<: *__tabularize_x_metadata
    transform_on_keys: ["val", "test"]

tabularize_y_val_test:
  transform:
    <<: *__tabularize_y_transform
    stride: ${task_definition.stride}
  metadata:
    <<: *__tabularize_y_metadata
    transform_on_keys: ["val", "test"]

concatenate_units_and_ragged2numpy:
  transform:
    _target_: picid.transforms.base_transforms.concatenate.MultiDatasetRuggedToDenseTransform
    axis: 1

  metadata:
    apply_to: ["features", "anomaly_detection"]
    assign_to: ["features", "anomaly_detection"]
