#@package _global_

defaults:
  - override /dataset: prognostics/concept_rul_multiunit_dataset
  - override /datamodule: base_datamodule_no_batch_sampler
  - override /model: tide
  - override /optimization: warmup_reduce_on_plateau

task_definition:
  requires_training: true

model:
  ts_in: ${task_definition.seq_len}
  ts_out: ${task_definition.pred_len}
  d_yc: 0
  d_yt: ${infer_data_dim:${task_definition.task_type},-1}
  d_x: ${infer_data_dim:features,-1}
  warmup_steps: ${infer_dataloader_length:train}
  mask_y_c: true
