
# Splitter depends on model and datasource, hence it should be defined automatically
_target_: picid.data.preprocessing.${datasource.splitter_type}
train: ${datasource.data_splits_params.train}  # int or float. In case of float it is a percentage of the dataset
val: ${datasource.data_splits_params.val}      # int or float. In case of float it is a percentage of the dataset
test: ${datasource.data_splits_params.test}    # int or float, or None. In case of float it is a percentage of the datasource. None means len(dataset) - (train + val)

# There values will be read from the model parameters similarly to how we deal with data_path.
seq_len: ${oc.select:model.seq_len,null}     # 96   # 384  # window size
label_len: ${oc.select:model.label_len,null} # 48 # 96  # overlap size
pred_len:  ${oc.select:model.pred_len,null}  #96  # prediction size
