_target_: picid.model.estimators.cnn1d.wrapper.CNN1D_Wrapper
task_type: ${task_definition.task_type}

input_channels: null
seq_len: null

output_channels: null
kernels: null
strides: null
dilations: null
latent_dim: null
dropout_prob: null
