_target_: picid.model.forecasters.lstm_model.LSTM_Forecaster

metadata:
  lightning_model: true

d_x: null # must be set by the model_config
d_yt: null # must be set by the model_config
d_yc: null # must be set by the model_config

hidden_dim: 32
n_layers: 2
task_type: ${task_definition.task_type}
