_target_: picid.model.estimators.window_average.wrapper.WindowAverageWrapper
task_type: ${task_definition.task_type}

# There values will be read from the model parameters similarly to how we deal with data_path.
seq_len: ${task_definition.seq_len} # window size
label_len: ${task_definition.label_len} # overlap size

# Model parameters
window_size_to_average: ${task_definition.seq_len}
pred_len: ${task_definition.pred_len} # prediction size

# Additional params needed for wrapper to run:
features_mode: ${datasource.task_mode}
device: "${trainer.accelerator}"
