_target_: picid.model.forecasters.spacetimeformer_model.Spacetimeformer_Forecaster

metadata:
  lightning_model: true

task_type: ${task_definition.task_type}
max_seq_len: null # must be set by the model_config
start_token_len: 6
d_yc: null # must be set by the model_config
d_yt: null # must be set by the model_config
d_x: null # must be set by the model_config
d_ff: 128
n_heads: 7
d_model: 128

use_revin: false
use_seasonal_decomp: false
e_layers: 2
d_layers: 3

global_cross_attn: "full"
global_self_attn: "full"
local_cross_attn: "full"
local_self_attn: "full"
time_emb_dim: 12
dropout_attn_matrix: 0.0
dropout_qkv: 0.1
dropout_emb: 0.0
dropout_ff: 0.2

pos_emb_type: abs
timetable_emb_type: linear
time_emb_type: linear
