defaults:
  - concepts_n_cmapss_multi/depater2023_default@_here_

# Emulate de Pater LSTM-AE preprocessing

# for rul: there is only 1 task and the history is fixed (here to 3)

# task_0: (t f1_0 f1_1 f1_2 f2_0 f2_1 f2_2 f3_0 f3_1 f3_2)  - rul 0 (training unit 1)
# task_0: (t f1_1 f1_2 f1_3 f2_1 f2_2 f2_3 f3_1 f3_2 f3_3)  - rul 1 (training unit 1)

# during test time, we are not using labels and we evaluate just one sample at a time
# for s in samples:
#   task_0: (f1_0 f1_1 f1_2 f2_0 f2_1 f2_2 f3_0 f3_1 f3_2)  - ? (testing unit 1)

# if your unit time is longer, we just add more of these samples to train

# if your evaluation is needs multiple rul predictions, then we slide across unit data
# with receptive field 3.
# We _never_ see or use any test labels here during model.fit().

# this is different from the batch_context case where we see in fit the testing labels!

# for forecasting:
# task_0: (f1_0 f1_1 f1_2 f2_0 f2_1 f2_2 f3_0 f3_1 f3_2)  - fc 0_0
# task_1: (f1_0 f1_1 f1_2 f2_0 f2_1 f2_2 f3_0 f3_1 f3_2)  - fc 0_1

# output from the model: full forecast (fc_0, fc_1)

tabularize_x_train:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - features: history

  metadata:
    apply_to: ["features"]
    assign_to: features
    transform_on_keys: ["train"]

tabularize_x_val_test:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - features: history

  metadata:
    apply_to: ["features"]
    assign_to: features
    transform_on_keys: ["val", "test"]

tabularize_y_train:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - rul: present

  metadata:
    apply_to: ["rul"]
    assign_to: rul
    transform_on_keys: ["train"]

tabularize_y_val_test:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - rul: present

  metadata:
    apply_to: ["rul"]
    assign_to: rul
    transform_on_keys: ["val", "test"]

tabularize_y_train_health_states:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - health_states: present

  metadata:
    apply_to: ["health_states"]
    assign_to: health_states
    transform_on_keys: ["train"]

tabularize_y_val_test_health_states:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - health_states: present

  metadata:
    apply_to: ["health_states"]
    assign_to: health_states
    transform_on_keys: ["val", "test"]

tabularize_y_train_concepts:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - concepts: present

  metadata:
    apply_to: ["concepts"]
    assign_to: concepts
    transform_on_keys: ["train"]

tabularize_y_val_test_concepts:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - concepts: present

  metadata:
    apply_to: ["concepts"]
    assign_to: concepts
    transform_on_keys: ["val", "test"]
# concatenate_units:
#   transform:
#     _target_: picid.transforms.base_transforms.concatenate.RuggedToDenseTransform
#   metadata:
#     apply_to: [features, rul, health_states, concepts]
#rename_target_to_fault_classification:
#  transform:
#    _target_: picid.transforms.base_transforms.identity.IdentityPassThrough
#
#  metadata:
#    apply_to: concepts
#    assign_to:
#      target: fault_classification
