seq_len: 48 # window size
label_len: 0 # overlap size
pred_len: 24 # prediction size
stride: 1
padding_left_flag: True # Ensure sequences are left-padded to have enough history and consistent lengths of train/val/test regardless of seq_len

task_type: forecasting

model:
  data_requirements:
    input_tensors:
      - features
      - time_features
      - target

target_metric: val/loss
target_metric_mode: min
