seq_len: 98 # window size
label_len: 48 # overlap size
padding_left_flag: True # Ensure sequences are left-padded to have enough history and consistent lengths of train/val/test regardless of seq_len
# TODO: harmonize and remove this config
# Note that here we have 96, but in the evaluatior
# we specify the effective prediction lenght 24
pred_len: 96
stride: 1

task_type: forecasting

model:
  data_requirements:
    input_tensors:
      - features
      - time_features
      - target

target_metric: val/loss
target_metric_mode: min
