# These scalers are pre-computed and do not need to be fitted on the data.

scaler_features:
  transform:
    _target_: picid.transforms.building.mzvav_scaler.MinMaxScalerMZVAV

  metadata:
    apply_to: features
    fit_on: train

rename_target_to_fault_classification:
  transform:
    _target_: picid.transforms.base_transforms.identity.IdentityPassThrough

  metadata:
    apply_to: target
    assign_to:
      target: fault_classification
