seq_len: 16
label_len: 0
pred_len: 0
task_type: fault_classification
padding_left_flag: true
stride: 1
stride_train: 5
num_classes: ${datasource.num_event_classes}
subset_ratio: 1.0
subset_seed: ${seed}

model:
  data_requirements:
    input_tensors:
      - features
      - ${task_definition.task_type}

target_metric: val/f1
target_metric_mode: max
