# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/datasets

# All the outputs are stored in the artifacts directory
# like model checkpoints, logs, plots, etc.
artifacts_dir: ${paths.root_dir}/artifacts

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}
ckpt_dir: ${paths.output_dir}/checkpoints
log_dir: ${paths.output_dir}/logs
plot_dir: ${paths.output_dir}/plots
eval_details: ${paths.output_dir}/eval_details
# Some models (e.g. Prophet) need a working directory to store temp files
model_workdir: ${paths.output_dir}/model_workdir
# For fit-predict tasks, we require a directory to store the fitted model for each task
model_cache_dir: ${paths.output_dir}/model_cache_dir

# path to working directory
work_dir: ${hydra:runtime.cwd}

cache_path: ${paths.data_dir}/cache/${datasource.data_name}
