#@package _global_

defaults:
  - override /dataset: state_forecasting/default
  - override /datamodule: base_datamodule
  - override /model: lstm
  - override /optimization: reduce_on_plateau

task_definition:
  requires_training: true

model:
  d_yc: ${infer_data_dim:features,-1}
  d_yt: ${infer_data_dim:features,-1}
  d_x: 0
