defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - model_timer
  - _self_

model_checkpoint:
  dirpath: ${paths.ckpt_dir}/checkpoints
  filename: "epoch{epoch:03d}-val_loss{val/loss:.8f}"
  monitor: ${task_definition.target_metric}
  mode: ${task_definition.target_metric_mode}
  auto_insert_metric_name: False
  save_weights_only: False
  save_top_k: 1
  save_last: False

early_stopping:
  # patience: ${trainer.max_epochs} #${trainer.min_epochs}
  patience: 25
  mode: ${task_definition.target_metric_mode}
  monitor: ${task_definition.target_metric}

model_summary:
  max_depth: -1

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "epoch"
