#@package _global_

defaults:
  - override /dataset: prognostics/rul_multiunit_dataset
  - override /datamodule: base_datamodule
  - override /model: crossformer
  - override /optimization: warmup_reduce_on_plateau_adam

task_definition:
  requires_training: true

model:
  ts_in: ${task_definition.seq_len}
  ts_out: 1 # task definition.pred_len is 0 for prognostics, but the model needs the output to be > 0, so we set it to 1 here
  d_yc: 0
  d_yt: ${infer_data_dim:${task_definition.task_type},-1}
  d_x: ${infer_data_dim:features,-1}
  seg_len: ${quot:${task_definition.seq_len},[10, 8, 12]}
  warmup_steps: ${infer_dataloader_length:train}
  # can only use time features if no future context available
  decoder_embedding: random
