#@package _global_

defaults:
  - override /dataset: prognostics/rul_multiunit_dataset
  - override /datamodule: base_datamodule
  - override /model: lstm
  - override /optimization: reduce_on_plateau

task_definition:
  requires_training: true

model:
  d_yc: 0
  d_yt: ${infer_data_dim:${task_definition.task_type},-1}
  d_x: ${infer_data_dim:features,-1}
