#@package _global_

defaults:
  - override /dataset: diagnostics/fault_classification_multiunit_dataset
  - override /datamodule: base_datamodule
  - override /model: cnn_1d
  - override /loss: CrossEntropy
  - override /optimization: reduce_on_plateau

task_definition:
  requires_training: true

model:
  seq_len: ${task_definition.seq_len}
  input_channels: ${infer_data_dim:features,-1}
  num_classes: ${task_definition.num_classes}
  # CNN_1D_DILATED, Receptive Field is 65
  output_channels: [16, 32, 64, 64, 64]
  kernels: [5, 5, 5, 5, 5]
  strides: [1, 1, 1, 1, 1]
  dilations: [1, 2, 4, 8, 1]
  latent_dim: 32
  dropout_prob: 0.2
