#@package _global_

defaults:
  # Disable wandb logger to avoid unnecessary network calls during debugging.
  - override /logger: csv

datamodule:
  num_workers: 0

datasource:
  cache_path: ${paths.cache_path}

trainer:
  accelerator: cpu
  devices: 1

# This will raise the original exception instead of a generic one.
# Making the debugger stop at the error, instead of the wrapper that we have for WANDB termination.
debug:
  raise_inner_exception: true

dataset:
  subset_range: [0, 5, 1] # Use only first 20 samples per task for faster model testing

# Due to artificially reduced dataset sizes, we cannot use the inverse scaling in the per-unit evaluator.
# So we disable it here for all of nox testing.
_evaluator_overrides: &evaluator_overrides
  save_predictions: False
  apply_inverse_scaling: False

evaluator:
  train: *evaluator_overrides
  val: *evaluator_overrides
  test: *evaluator_overrides
