#@package _global_

defaults:
  # Disable wandb logger to avoid unnecessary network calls during debugging.
  - default
  - override /logger: csv

datasource:
  debug_cache_dataset: true
  debug_cache_path: ${paths.data_dir}/debug_cache
  debug_subsample_rate: 25

trainer:
  max_epochs: 5

# This will raise the original exception instead of a generic one.
# Making the debugger stop at the error, instead of the wrapper that we have for WANDB termination.
debug:
  raise_inner_exception: true
