_target_: picid.data.datasources.airbus_helicopter.AirbusHelicopterLoader
data_name: airbus_helicopter
task_mode: anomaly_detection  # rul, fault
data_dir: ${paths.data_dir}
cache_dir: ${paths.data_dir}/phmd_cache


num_classes: 2  # Healthy or Not healthy, TODO: discuss with R whenever it is a good idea to trean it as multiclass classification (easier to adapt in the pipeline)
