# Setup taken from https://www.sciencedirect.com/science/article/pii/S0952197622005723

_target_: picid.data.datasources.base.multi_source_loader.MultiSourceLoader
_recursive_: False

# Must have keys for the pipeline
data_name: MultiSource_concepts_N-CMAPSS
task_mode: rul

defaults:
  - /datasource@train1: concepts_n_cmapss
  - /datasource@test1: concepts_n_cmapss
  - /datasource@val1: concepts_n_cmapss

source_list:
  train1: ${..train1}
  test1: ${..test1}
  val1: ${..val1}

multisource_data_splitter:
  _target_: picid.data.preprocessing.BySourceSplitter
  sources_train: [train1]
  sources_test: [test1]
  sources_val: [val1]

train1:
  load_arguments:
    n_DS: "03"
    fc: 1
    mode: "train"
  group_by_unit: True

test1:
  load_arguments:
    n_DS: "03"
    fc: 2
    mode: "test"
  group_by_unit: True

val1:
  load_arguments:
    n_DS: "03"
    fc: 3
    mode: "train"
  group_by_unit: True
