_target_: picid.data.datasources.phmd_phme20.PHME20Loader
fold: 0
data_name: PHME20
task_mode: rul # rul, fault
auxiliary_tasks: [] # When we want to have fault as main task, we can use rul as auxiliary task
cache_dir: ${paths.data_dir}/phmd_cache
