_target_: picid.data.datasources.phmd_xjtu_sy.XJTU_SYLoader
fold: 0
data_name: XJTU-SY
task_mode: rul # rul, fault
auxiliary_tasks: [] # When we want to have fault as main task, we can use rul as auxiliary task
cache_dir: ${paths.data_dir}/phmd_cache
split_mode: in_domain
fold_id: 1
split_assignments_by_mode:
  in_domain:
    fold_1:
      train: ["1_3", "1_4", "1_5", "2_3", "2_4", "2_5", "3_3", "3_4", "3_5"]
      val: ["1_1", "2_1", "3_1"]
      test: ["1_2", "2_2", "3_2"]
    fold_2:
      train: ["1_1", "1_4", "1_5", "2_1", "2_4", "2_5", "3_1", "3_4", "3_5"]
      val: ["1_2", "2_2", "3_2"]
      test: ["1_3", "2_3", "3_3"]
    fold_3:
      train: ["1_1", "1_2", "1_5", "2_1", "2_2", "2_5", "3_1", "3_2", "3_5"]
      val: ["1_3", "2_3", "3_3"]
      test: ["1_4", "2_4", "3_4"]
    fold_4:
      train: ["1_1", "1_2", "1_3", "2_1", "2_2", "2_3", "3_1", "3_2", "3_3"]
      val: ["1_4", "2_4", "3_4"]
      test: ["1_5", "2_5", "3_5"]
    fold_5:
      train: ["1_2", "1_3", "1_4", "2_2", "2_3", "2_4", "3_2", "3_3", "3_4"]
      val: ["1_5", "2_5", "3_5"]
      test: ["1_1", "2_1", "3_1"]
  domain_shift:
    fold_1:
      train: ["1_2", "1_3", "1_4", "1_5", "2_2", "2_3", "2_4", "2_5"]
      val: ["1_1", "2_1"]
      test: ["3_1", "3_2", "3_3", "3_4", "3_5"]
    fold_2:
      train: ["1_1", "1_3", "1_4", "1_5", "2_1", "2_3", "2_4", "2_5"]
      val: ["1_2", "2_2"]
      test: ["3_1", "3_2", "3_3", "3_4", "3_5"]
    fold_3:
      train: ["1_1", "1_2", "1_4", "1_5", "2_1", "2_2", "2_4", "2_5"]
      val: ["1_3", "2_3"]
      test: ["3_1", "3_2", "3_3", "3_4", "3_5"]
    fold_4:
      train: ["1_1", "1_2", "1_3", "1_5", "2_1", "2_2", "2_3", "2_5"]
      val: ["1_4", "2_4"]
      test: ["3_1", "3_2", "3_3", "3_4", "3_5"]
    fold_5:
      train: ["1_1", "1_2", "1_3", "1_4", "2_1", "2_2", "2_3", "2_4"]
      val: ["1_5", "2_5"]
      test: ["3_1", "3_2", "3_3", "3_4", "3_5"]

  phmd_split:
    train: ["1_3", "1_4", "2_1", "2_4", "2_5", "3_1", "3_2", "3_3"]
    val: ["1_1", "1_2", "3_5"]
    test: ["1_5", "2_2", "2_3", "3_4"]

use_ragged: True # This flag at the end assumed to be true by def
