defaults:
  - concepts_n_cmapss/depater2023_default@_here_

# Emulate de Pater LSTM-AE preprocessing

tabularize_x_train:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - features: history

  metadata:
    apply_to: ["features"]
    assign_to: features
    transform_on_keys: ["train"]

tabularize_x_val_test:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - features: history

  metadata:
    apply_to: ["features"]
    assign_to: features
    transform_on_keys: ["val", "test"]

tabularize_y_train:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - rul: present

  metadata:
    apply_to: ["rul"]
    assign_to: rul
    transform_on_keys: ["train"]

tabularize_y_val_test:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - rul: present

  metadata:
    apply_to: ["rul"]
    assign_to: rul
    transform_on_keys: ["val", "test"]

tabularize_y_train_health_states:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - health_states: present

  metadata:
    apply_to: ["health_states"]
    assign_to: health_states
    transform_on_keys: ["train"]

tabularize_y_val_test_health_states:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - health_states: present

  metadata:
    apply_to: ["health_states"]
    assign_to: health_states
    transform_on_keys: ["val", "test"]

tabularize_y_train_concepts:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride_train}
    padding_left_flag: ${task_definition.padding_left_flag}
    subset_ratio: ${oc.select:task_definition.subset_ratio,null}
    subset_seed: ${oc.select:task_definition.subset_seed,null}
    subset_blocks: ${oc.select:task_definition.subset_blocks,null}
    timestep_dimension: 1

    select_features:
      - concepts: present

  metadata:
    apply_to: ["concepts"]
    assign_to: concepts
    transform_on_keys: ["train"]

tabularize_y_val_test_concepts:
  # Concatenate time-features to the feature set
  transform:
    _target_: picid.transforms.base_transforms.tabularizers.TimeseriesTabularizer
    seq_len: ${task_definition.seq_len}
    label_len: ${task_definition.label_len}
    pred_len: ${task_definition.pred_len}
    stride: ${task_definition.stride}
    padding_left_flag: ${task_definition.padding_left_flag}
    timestep_dimension: 1

    select_features:
      - concepts: present

  metadata:
    apply_to: ["concepts"]
    assign_to: concepts
    transform_on_keys: ["val", "test"]
# concatenate_units:
#   transform:
#     _target_: picid.transforms.base_transforms.concatenate.RuggedToDenseTransform
#   metadata:
#     apply_to: [features, rul, health_states, concepts]
